### ISSUE TITLE
Error in generating path

### ISSUE THREAD

**Issue by samsonjm** [mohimanilab/MS2Planner#2]
When trying to run path_finder apex using either my own data or your test data (Blank_to_Sample_mrgd.csv), I am getting the following error:

```2022-02-08 13:05:35,328 - path_finder - INFO - =============
2022-02-08 13:05:35,328 - path_finder - INFO - Apex mode begin
2022-02-08 13:05:35,328 - path_finder - INFO - =============
2022-02-08 13:05:35,328 - path_finder - INFO - File Read
2022-02-08 13:05:35,328 - path_finder - INFO - =============
2022-02-08 13:05:35,328 - path_finder - INFO - Begin Finding Path
2022-02-08 13:05:35,328 - path_finder - INFO - =============
2022-02-08 13:05:35,328 - path_finder - ERROR - error in generating path
Traceback (most recent call last):
  File "/home/samsonjm/ExternalTools/MS2Planner/MS2Planner/path_finder.py", line 186, in <module>
    paths_rt, paths_mz, paths_charge, edge_intensity_dic = apex.PathGen(
  File "/home/samsonjm/ExternalTools/MS2Planner/MS2Planner/path_apex.py", line 168, in PathGen
    _, _, _, _, edge_intensity_dic = NodeEdge1Create(
  File "/home/samsonjm/ExternalTools/MS2Planner/MS2Planner/path_apex.py", line 52, in NodeEdge1Create
    right_node = data[i, 1] + 0.5 * rt_isolation + delay
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'
~                                                                      
```

Here is what I used to call the program:
```python3 path_finder.py apex /path/to/Blank_to_Sample_mrgd.csv /path/to/output.csv 5000 3 5 -intensity_accu 1d6 -isolation 5  -min_scan 200 -max_scan 2200```

Have I done something wrong, or is this an error in the code?

**Comment by samsonjm** [comment]
The issue was in -min_scan and -max_scan, I misinterpreted the meaning of the parameters.
